Repository ltlaitoff/pomodoro-timer, pull requests merged in 2024-06, with the labels that each got.

#7 Change pomodoro timers default value to normal
  src/store/userSettingsStore.ts
Labels: bug

#6 Rename default category
  src/store/categoriesStore.ts
Labels: feature

#8 Import and use i18n
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/assets/i18n/en/translation.json
  src/components/LeftPanel/CategoryForm.vue
  src/components/LeftPanel/CategoryPanel.vue
  src/components/LeftPanel/SettingsPanel.vue
  src/components/LeftPanel/StatisticPanel.vue
  src/main.ts
Labels: feature

#9 Staging v0.1.0
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/assets/i18n/en/translation.json
  src/components/LeftPanel/CategoryForm.vue
  src/components/LeftPanel/CategoryPanel.vue
  src/components/LeftPanel/SettingsPanel.vue
  src/components/LeftPanel/StatisticPanel.vue
  src/main.ts
  src/store/categoriesStore.ts
  src/store/userSettingsStore.ts
Labels: staging
